version: "3"

services:
  app:
    build:
      context: "."
    command: "sh -c \"python manage.py wait_for_db &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000\"\n"
    ports:
      - "8000:8000"
    user: "root:root"
    volumes:
      - "./app:/app"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    image: "postgres:10-alpine"
